# Generated by Django 4.0.5 on 2022-06-12 18:42

import django.core.validators
from django.db import migrations, models
import object3D.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Object3D',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('usage', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Object 3D',
                'verbose_name_plural': 'Objects 3D',
            },
        ),
        migrations.CreateModel(
            name='ResourceFile',
            fields=[
                ('title', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('fileType', models.CharField(choices=[('general', 'General File'), ('geometry', 'Geometry File'), ('object', 'Object File'), ('material', 'Material File'), ('texture', 'Texture File'), ('image', 'Image File'), ('audio', 'Audio File'), ('animation', 'Animation File')], default='general', max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('filePath', models.FileField(upload_to=object3D.models.ResourceFile.uploadPath)),
                ('assignedObjects', models.ManyToManyField(blank=True, related_name='filesRelated', to='object3D.object3d')),
            ],
            options={
                'verbose_name': 'Resource File',
                'verbose_name_plural': 'Resource Files',
            },
        ),
    ]
